// src/lib/components/review/ReviewPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for ReviewPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const ReviewPanel = lazy(() => import('./ReviewPanel.tsx'));

export default function ReviewPanelLazy() {
  return (
    <Suspense fallback={null}>
      <ReviewPanel />
    </Suspense>
  );
}

// src/lib/components/review/ReviewPanelLazy.svelte
<!--
  Lazy boundary for ReviewPanel — see EditorPanelLazy for the rationale. Loaded
  on demand; rendered in place of ReviewPanel so call sites stay unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./ReviewPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}
