// src/lib/components/http/HttpClientPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for HttpClientPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const HttpClientPanel = lazy(() => import('./HttpClientPanel.tsx'));

export default function HttpClientPanelLazy() {
  return (
    <Suspense fallback={null}>
      <HttpClientPanel />
    </Suspense>
  );
}

// src/lib/components/http/HttpClientPanelLazy.svelte
<!--
  Lazy boundary for HttpClientPanel — see EditorPanelLazy for the rationale.
  Loaded on demand; rendered in place of HttpClientPanel so call sites stay
  unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./HttpClientPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}
