// src/lib/components/shared/Dropdown.tsx
import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { createPortal } from 'react-dom';
import './Dropdown.css';

// Premium custom dropdown matching the app's picker language (see
// FloatingPromptBar target-picker): frosted popover, rounded items, accent
// active state. Replaces native <select> so menus feel consistent.
export type DropdownOption = {
  value: string;
  label: string;
  sublabel?: string;
  color?: string;
  disabled?: boolean;
};

interface DropdownProps {
  options: DropdownOption[];
  value: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  ariaLabel?: string;
  disabled?: boolean;
}

// Menu max-height (keep in sync with .dd-menu max-height in CSS).
const MENU_MAX = 260;

export default function Dropdown({
  options,
  value,
  onChange,
  placeholder = 'Select…',
  ariaLabel = 'Select an option',
  disabled = false,
}: DropdownProps) {
  const [open, setOpen] = useState(false);
  const [dropUp, setDropUp] = useState(false);
  const [menuStyle, setMenuStyle] = useState<CSSProperties>({});
  const rootEl = useRef<HTMLDivElement | null>(null);
  const menuEl = useRef<HTMLDivElement | null>(null);

  const selected = options.find((o) => o.value === value) ?? null;

  /**
   * Position the menu. It is portaled to <body> with `position: fixed` so it can
   * never be clipped by an ancestor's `overflow` (the room panels that host this
   * dropdown clip their content), and the available space decides whether it
   * opens up or down and how tall it can grow before it scrolls.
   */
  const updatePlacement = useCallback(() => {
    if (!rootEl.current) return;
    const r = rootEl.current.getBoundingClientRect();
    const below = window.innerHeight - r.bottom;
    const above = r.top;
    const willDropUp = below < Math.min(MENU_MAX, 200) && above > below;
    setDropUp(willDropUp);

    const maxHeight = Math.max(120, Math.min(MENU_MAX, (willDropUp ? above : below) - 12));
    const next: CSSProperties = {
      position: 'fixed',
      left: r.left,
      width: r.width,
      maxHeight,
    };
    if (willDropUp) {
      next.bottom = window.innerHeight - r.top + 6;
    } else {
      next.top = r.bottom + 6;
    }
    setMenuStyle(next);
  }, []);

  function toggle() {
    if (disabled) return;
    if (!open) updatePlacement();
    setOpen((o) => !o);
  }

  function choose(option: DropdownOption) {
    if (option.disabled) return;
    onChange?.(option.value);
    setOpen(false);
  }

  function onKeydown(e: React.KeyboardEvent) {
    if (e.key === 'Escape' && open) {
      e.stopPropagation();
      setOpen(false);
      return;
    }
    if ((e.key === 'Enter' || e.key === ' ') && !open) {
      e.preventDefault();
      updatePlacement();
      setOpen(true);
      return;
    }
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
      e.preventDefault();
      if (!open) {
        updatePlacement();
        setOpen(true);
        return;
      }
      const enabled = options.filter((o) => !o.disabled);
      if (enabled.length === 0) return;
      const idx = enabled.findIndex((o) => o.value === value);
      const next =
        e.key === 'ArrowDown'
          ? enabled[Math.min(enabled.length - 1, idx + 1)]
          : enabled[Math.max(0, idx - 1)];
      if (next) onChange?.(next.value);
    }
  }

  useEffect(() => {
    if (!open) return;
    const handlePointer = (e: MouseEvent) => {
      const target = e.target as Node;
      // The menu is portaled outside `rootEl`, so it must be checked separately —
      // otherwise clicking an option would register as an outside click and close
      // the menu before the selection fires.
      if (rootEl.current?.contains(target)) return;
      if (menuEl.current?.contains(target)) return;
      setOpen(false);
    };
    const reposition = () => updatePlacement();
    window.addEventListener('mousedown', handlePointer);
    window.addEventListener('scroll', reposition, true);
    window.addEventListener('resize', reposition);
    return () => {
      window.removeEventListener('mousedown', handlePointer);
      window.removeEventListener('scroll', reposition, true);
      window.removeEventListener('resize', reposition);
    };
  }, [open, updatePlacement]);

  return (
    <div className="dropdown" ref={rootEl}>
      <button
        type="button"
        className={`dd-trigger${open ? ' open' : ''}`}
        disabled={disabled}
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-label={ariaLabel}
        onClick={toggle}
        onKeyDown={onKeydown}
      >
        {selected?.color && <span className="dd-dot" style={{ background: selected.color }}></span>}
        <span className={`dd-value${!selected ? ' placeholder' : ''}`}>
          {selected?.label ?? placeholder}
        </span>
        <svg
          className="dd-chevron"
          width="11"
          height="11"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>

      {open &&
        createPortal(
          <div
            ref={menuEl}
            className={`dd-menu${dropUp ? ' drop-up' : ''}`}
            role="listbox"
            aria-label={ariaLabel}
            style={menuStyle}
          >
            {options.map((option) => (
              <button
                key={option.value}
                type="button"
                className={`dd-item${option.value === value ? ' active' : ''}`}
                disabled={option.disabled}
                role="option"
                aria-selected={option.value === value}
                onClick={() => choose(option)}
              >
                {option.color && <span className="dd-dot" style={{ background: option.color }}></span>}
                <span className="dd-item-label">{option.label}</span>
                {option.sublabel && <span className="dd-item-sub">{option.sublabel}</span>}
                {option.value === value && (
                  <svg
                    className="dd-check"
                    width="13"
                    height="13"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2.5"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                )}
              </button>
            ))}
          </div>,
          document.body,
        )}
    </div>
  );
}

// src/lib/components/shared/Dropdown.svelte
<script module lang="ts">
  // Premium custom dropdown matching the app's picker language (see
  // FloatingPromptBar target-picker): frosted popover, rounded items, accent
  // active state. Replaces native <select> so menus feel consistent.
  export type DropdownOption = {
    value: string;
    label: string;
    sublabel?: string;
    color?: string;
    disabled?: boolean;
  };
</script>

<script lang="ts">
  let {
    options,
    value = $bindable(),
    onChange,
    placeholder = 'Select…',
    ariaLabel = 'Select an option',
    disabled = false,
  }: {
    options: DropdownOption[];
    value: string;
    onChange?: (value: string) => void;
    placeholder?: string;
    ariaLabel?: string;
    disabled?: boolean;
  } = $props();

  let open = $state(false);
  let dropUp = $state(false);
  let rootEl = $state<HTMLDivElement | null>(null);

  let selected = $derived(options.find((o) => o.value === value) ?? null);

  // Menu max-height (keep in sync with .dd-menu max-height below).
  const MENU_MAX = 260;

  /** Decide whether to open upward: when there isn't room below but there is above. */
  function updatePlacement() {
    if (!rootEl) return;
    const r = rootEl.getBoundingClientRect();
    const below = window.innerHeight - r.bottom;
    const above = r.top;
    dropUp = below < Math.min(MENU_MAX, 200) && above > below;
  }

  function toggle() {
    if (disabled) return;
    if (!open) updatePlacement();
    open = !open;
  }

  function choose(option: DropdownOption) {
    if (option.disabled) return;
    value = option.value;
    onChange?.(option.value);
    open = false;
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && open) {
      e.stopPropagation();
      open = false;
      return;
    }
    if ((e.key === 'Enter' || e.key === ' ') && !open) {
      e.preventDefault();
      updatePlacement();
      open = true;
      return;
    }
    if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
      e.preventDefault();
      if (!open) { updatePlacement(); open = true; return; }
      const enabled = options.filter((o) => !o.disabled);
      if (enabled.length === 0) return;
      const idx = enabled.findIndex((o) => o.value === value);
      const next = e.key === 'ArrowDown'
        ? enabled[Math.min(enabled.length - 1, idx + 1)]
        : enabled[Math.max(0, idx - 1)];
      if (next) { value = next.value; onChange?.(next.value); }
    }
  }

  $effect(() => {
    if (!open) return;
    const handlePointer = (e: MouseEvent) => {
      if (rootEl && !rootEl.contains(e.target as Node)) open = false;
    };
    window.addEventListener('mousedown', handlePointer);
    return () => window.removeEventListener('mousedown', handlePointer);
  });
</script>

<div class="dropdown" bind:this={rootEl}>
  <button
    type="button"
    class="dd-trigger"
    class:open
    {disabled}
    aria-haspopup="listbox"
    aria-expanded={open}
    aria-label={ariaLabel}
    onclick={toggle}
    onkeydown={onKeydown}
  >
    {#if selected?.color}
      <span class="dd-dot" style="background: {selected.color};"></span>
    {/if}
    <span class="dd-value" class:placeholder={!selected}>{selected?.label ?? placeholder}</span>
    <svg class="dd-chevron" width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
      <polyline points="6 9 12 15 18 9" />
    </svg>
  </button>

  {#if open}
    <div class="dd-menu" class:drop-up={dropUp} role="listbox" aria-label={ariaLabel}>
      {#each options as option (option.value)}
        <button
          type="button"
          class="dd-item"
          class:active={option.value === value}
          disabled={option.disabled}
          role="option"
          aria-selected={option.value === value}
          onclick={() => choose(option)}
        >
          {#if option.color}
            <span class="dd-dot" style="background: {option.color};"></span>
          {/if}
          <span class="dd-item-label">{option.label}</span>
          {#if option.sublabel}
            <span class="dd-item-sub">{option.sublabel}</span>
          {/if}
          {#if option.value === value}
            <svg class="dd-check" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12" />
            </svg>
          {/if}
        </button>
      {/each}
    </div>
  {/if}
</div>

<style>
  .dropdown {
    position: relative;
    min-width: 0;
  }

  .dd-trigger {
    width: 100%;
    height: 30px;
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 0 8px;
    background: rgba(var(--bg-secondary-rgb, 18, 18, 22), 0.5);
    border: 1px solid var(--border);
    border-radius: 7px;
    color: var(--text-secondary);
    font-size: 11.5px;
    cursor: pointer;
    transition: border-color 0.15s, background 0.15s, color 0.15s;
  }
  .dd-trigger:hover:not(:disabled) {
    border-color: var(--border-focus);
    color: var(--text-primary);
  }
  .dd-trigger.open {
    border-color: var(--accent);
    background: rgba(var(--bg-secondary-rgb, 18, 18, 22), 0.7);
  }
  .dd-trigger:disabled {
    opacity: 0.45;
    cursor: not-allowed;
  }

  .dd-value {
    flex: 1;
    min-width: 0;
    text-align: left;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-weight: 550;
    color: var(--text-primary);
  }
  .dd-value.placeholder {
    color: var(--text-muted);
    font-weight: 500;
  }

  .dd-chevron {
    flex-shrink: 0;
    opacity: 0.55;
    transition: transform 0.18s ease, opacity 0.15s;
  }
  .dd-trigger.open .dd-chevron {
    transform: rotate(180deg);
    opacity: 0.9;
  }

  .dd-dot {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    flex-shrink: 0;
  }

  .dd-menu {
    position: absolute;
    top: calc(100% + 6px);
    left: 0;
    right: 0;
    transform-origin: top;
    background: color-mix(in srgb, var(--bg-secondary) 96%, transparent);
    backdrop-filter: blur(18px);
    -webkit-backdrop-filter: blur(18px);
    border: 1px solid color-mix(in srgb, var(--accent) 20%, var(--border));
    border-radius: 12px;
    padding: 5px;
    display: flex;
    flex-direction: column;
    gap: 2px;
    box-shadow: 0 12px 32px rgba(0, 0, 0, 0.26);
    z-index: 40;
    max-height: 260px;
    overflow-y: auto;
    scrollbar-width: thin;
    scrollbar-color: var(--scrollbar-thumb) transparent;
    animation: dd-pop 0.13s ease;
  }
  .dd-menu.drop-up {
    top: auto;
    bottom: calc(100% + 6px);
    transform-origin: bottom;
    animation: dd-pop-up 0.13s ease;
  }

  @keyframes dd-pop {
    from { opacity: 0; transform: translateY(-4px); }
    to   { opacity: 1; transform: translateY(0); }
  }
  @keyframes dd-pop-up {
    from { opacity: 0; transform: translateY(4px); }
    to   { opacity: 1; transform: translateY(0); }
  }

  .dd-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 7px 9px;
    border: 0;
    border-radius: 8px;
    background: transparent;
    color: var(--text-secondary);
    font-size: 12px;
    text-align: left;
    cursor: pointer;
    transition: background 0.12s, color 0.12s;
  }
  .dd-item:hover:not(:disabled) {
    background: var(--bg-hover);
    color: var(--text-primary);
  }
  .dd-item.active {
    background: color-mix(in srgb, var(--accent) 14%, var(--bg-primary));
    color: var(--text-primary);
  }
  .dd-item:disabled {
    opacity: 0.4;
    cursor: not-allowed;
  }

  .dd-item-label {
    flex: 1;
    min-width: 0;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-weight: 500;
  }
  .dd-item-sub {
    font-size: 10px;
    color: var(--text-muted);
    font-family: var(--font-mono, monospace);
    flex-shrink: 0;
  }
  .dd-check {
    color: var(--accent);
    flex-shrink: 0;
  }
</style>
