// src/lib/components/shared/StickyContainer.tsx
import type { ReactNode } from 'react';
import './StickyContainer.css';

interface Props {
  stickyTop?: boolean;
  stickyBottom?: boolean;
  className?: string;
  /** `topContent`/`bottomContent` snippets become React nodes. */
  topContent?: ReactNode;
  bottomContent?: ReactNode;
  children?: ReactNode;
}

export default function StickyContainer({
  stickyTop = false,
  stickyBottom = false,
  className = '',
  topContent,
  bottomContent,
  children,
}: Props) {
  return (
    <div className={`sticky-container ${className}`}>
      {stickyTop && topContent && <div className="sticky-wrapper sticky-top">{topContent}</div>}

      <div className="sticky-content">{children}</div>

      {stickyBottom && bottomContent && (
        <div className="sticky-wrapper sticky-bottom">{bottomContent}</div>
      )}
    </div>
  );
}

// src/lib/components/shared/StickyContainer.svelte
<script lang="ts">
  interface Props {
    stickyTop?: boolean;
    stickyBottom?: boolean;
    class?: string;
    topContent?: import('svelte').Snippet;
    bottomContent?: import('svelte').Snippet;
    children?: import('svelte').Snippet;
  }

  let { 
    stickyTop = false, 
    stickyBottom = false, 
    class: className = '',
    topContent,
    bottomContent,
    children 
  }: Props = $props();
</script>

<div class="sticky-container {className}">
  {#if stickyTop && topContent}
    <div class="sticky-wrapper sticky-top">
      {@render topContent()}
    </div>
  {/if}
  
  <div class="sticky-content">
    {@render children?.()}
  </div>
  
  {#if stickyBottom && bottomContent}
    <div class="sticky-wrapper sticky-bottom">
      {@render bottomContent()}
    </div>
  {/if}
</div>

<style>
  .sticky-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow: hidden;
  }

  .sticky-wrapper {
    flex-shrink: 0;
  }

  .sticky-top {
    position: sticky;
    top: 0;
    z-index: 50;
    background: var(--bg-secondary);
  }

  .sticky-bottom {
    position: sticky;
    bottom: 0;
    z-index: 49;
    background: var(--bg-secondary);
  }

  .sticky-content {
    flex: 1;
    overflow-y: auto;
    overflow-x: hidden;
    min-height: 0;
  }
</style>
