// src/lib/components/pet/DevPetPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for DevPetPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const DevPetPanel = lazy(() => import('./DevPetPanel.tsx'));

export default function DevPetPanelLazy() {
  return (
    <Suspense fallback={null}>
      <DevPetPanel />
    </Suspense>
  );
}

// src/lib/components/pet/DevPetPanelLazy.svelte
<!--
  Lazy boundary for DevPetPanel — see EditorPanelLazy for the rationale. Loaded
  on demand; rendered in place of DevPetPanel so call sites stay unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./DevPetPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}
