// src/lib/components/pet/DevPetPanel.svelte
<script lang="ts">
  import { devpet } from '$lib/stores/devpet';
  import { showToast } from '$lib/stores/notification';
  import PetAvatar from './PetAvatar.svelte';

  let renameMode = $state(false);
  let newName = $state('');

  const companionTypes = [
    { id: 'cat' as const, label: 'Cat', desc: 'Warm and focused' },
    { id: 'slime' as const, label: 'Slime', desc: 'Soft and lively' },
    { id: 'robo' as const, label: 'Robo', desc: 'Sharp and precise' },
  ];

  let bubbleText = $derived.by(() => {
    switch ($devpet.status) {
      case 'sleep':
        return 'zZz... recharging quietly.';
      case 'typing':
        return $devpet.wpm > 60 ? `Fast flow: ${$devpet.wpm} WPM.` : `Typing rhythm: ${$devpet.wpm} WPM.`;
      case 'commit':
        return 'Commit logged. Clean work.';
      case 'happy':
        return 'That hit the spot.';
      case 'eating':
        return 'Snack break accepted.';
      case 'idle':
      default:
        return 'Ready when you are.';
    }
  });

  let xpProgress = $derived(
    Math.max(0, Math.min(100, ($devpet.xp / Math.max(1, $devpet.xpToNextLevel)) * 100))
  );
  let xpDisplay = $derived(Math.round($devpet.xp));
  let xpToNextDisplay = $derived(Math.round($devpet.xpToNextLevel));
  let xpRemaining = $derived(Math.max(0, xpToNextDisplay - xpDisplay));

  function handleFeed() {
    if ($devpet.coins < 10) {
      showToast('Not enough coins. Write more code to earn coins.', 'warning');
      return;
    }
    const success = devpet.feed();
    if (success) {
      showToast(`${$devpet.name} enjoyed the snack. (+15 XP)`, 'success');
    }
  }

  function handlePet() {
    devpet.pet();
  }

  function startRename() {
    newName = $devpet.name;
    renameMode = true;
  }

  function saveRename() {
    const trimmed = newName.trim();
    if (!trimmed) return;
    devpet.rename(trimmed);
    renameMode = false;
    showToast(`Renamed companion to ${trimmed}.`, 'success');
  }

  function switchType(type: 'cat' | 'slime' | 'robo') {
    devpet.setType(type);
    showToast(`Switched companion to ${type}.`, 'info');
  }
</script>

<div class="devpet-panel">
  <div class="devpet-container scrollable">
    <section class="pet-hero" aria-label="DevPet companion">
      <div class="pet-hero-topline">
        <span class="eyebrow">DevPet</span>
        <span class="status-pill" data-status={$devpet.status}>{$devpet.status}</span>
      </div>

      <div class="pet-stage-shell">
        <div class="pet-bubble" aria-live="polite">{bubbleText}</div>

        <button class="pet-avatar-stage" onclick={handlePet} title="Pet companion" aria-label="Pet {$devpet.name}">
          <PetAvatar type={$devpet.type} status={$devpet.status} skin={$devpet.skin} />
        </button>

        {#if $devpet.status === 'happy'}
          <span class="sparkle s1"></span>
          <span class="sparkle s2"></span>
          <span class="sparkle s3"></span>
        {/if}
      </div>

      <div class="pet-identity">
        {#if renameMode}
          <div class="rename-row">
            <input
              type="text"
              class="rename-input"
              bind:value={newName}
              maxlength="16"
              onkeydown={(e) => e.key === 'Enter' && saveRename()}
              aria-label="New companion name"
            />
            <button class="action-btn-sm save-btn" onclick={saveRename}>Save</button>
            <button class="action-btn-sm cancel-btn" onclick={() => (renameMode = false)}>Cancel</button>
          </div>
        {:else}
          <div class="name-display">
            <h2>{$devpet.name}</h2>
            <button class="edit-btn" onclick={startRename} aria-label="Rename companion">
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 20h9" />
                <path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z" />
              </svg>
            </button>
          </div>
        {/if}
        <span class="type-badge">Level {$devpet.level} {$devpet.type}</span>
      </div>

      <div class="hero-metrics">
        <div class="metric-chip">
          <span class="metric-label">Coins</span>
          <span class="metric-value">{$devpet.coins}</span>
        </div>
        <div class="metric-chip">
          <span class="metric-label">WPM</span>
          <span class="metric-value">{$devpet.wpm}</span>
        </div>
        <div class="metric-chip">
          <span class="metric-label">XP</span>
          <span class="metric-value">{xpDisplay}</span>
        </div>
      </div>
    </section>

    <div class="devpet-aside">
      <section class="progress-card bento-card">
        <div class="section-heading">
          <span>Progress</span>
          <strong>{xpDisplay} / {xpToNextDisplay} XP</strong>
        </div>
        <div class="progress-container" aria-label="Experience progress">
          <div class="progress-bar" style="width: {xpProgress}%"></div>
        </div>
        <p class="stat-footer">Need {xpRemaining} XP to level up</p>
      </section>

      <section class="controls-grid">
        <div class="bento-card care-card">
          <div class="section-heading">
            <span>Care</span>
            <strong>{$devpet.totalFeedCount} snacks</strong>
          </div>
          <div class="care-buttons">
            <button class="action-btn feed-btn" onclick={handleFeed} disabled={$devpet.coins < 10}>
              <span class="btn-icon" aria-hidden="true">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M4 11a8 8 0 0 1 16 0" />
                  <path d="M3 11h18" />
                  <path d="M5 15h14" />
                  <path d="M6 19h12" />
                </svg>
              </span>
              <span>Feed snack</span>
              <small>10 coins</small>
            </button>

            <button class="action-btn play-btn" onclick={handlePet}>
              <span class="btn-icon" aria-hidden="true">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21.2l7.7-7.7 1.1-1.1a5.5 5.5 0 0 0 0-7.8Z" />
                </svg>
              </span>
              <span>Pet companion</span>
              <small>Free</small>
            </button>
          </div>
        </div>

        <div class="bento-card type-card">
          <div class="section-heading">
            <span>Companion</span>
            <strong>{$devpet.type}</strong>
          </div>
          <div class="type-grid">
            {#each companionTypes as option (option.id)}
              <button
                type="button"
                class="type-btn"
                class:active={$devpet.type === option.id}
                onclick={() => switchType(option.id)}
              >
                <span>{option.label}</span>
                <small>{option.desc}</small>
              </button>
            {/each}
          </div>
        </div>
      </section>

      <section class="bento-card stats-overview">
        <div class="section-heading">
          <span>Workspace stats</span>
          <strong>Lifetime</strong>
        </div>
        <div class="stats-grid">
          <div class="stat-item">
            <span class="val">{$devpet.totalCharactersTyped.toLocaleString()}</span>
            <span class="lbl">Characters</span>
          </div>
          <div class="stat-item">
            <span class="val">{$devpet.totalCommits}</span>
            <span class="lbl">Commits</span>
          </div>
          <div class="stat-item">
            <span class="val">{$devpet.totalFeedCount}</span>
            <span class="lbl">Snacks</span>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

<style>
  .devpet-panel {
    display: flex;
    flex-direction: column;
    height: 100%;
    width: 100%;
    overflow: hidden;
    background: transparent;
    container-type: size;
  }

  .devpet-aside {
    display: flex;
    flex-direction: column;
    gap: 10px;
    width: 100%;
    container-type: inline-size;
  }

  .devpet-container {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 10px;
    width: 100%;
    min-height: 0;
    overflow-y: auto;
    overflow-x: hidden;
    overscroll-behavior: none;
    scrollbar-gutter: stable;
    padding: clamp(10px, 3cqw, 16px);
  }

  .pet-hero {
    display: flex;
    flex-direction: column;
    align-items: center;
    position: relative;
    overflow: clip;
    padding: clamp(14px, 4cqw, 22px);
    border: 1px solid color-mix(in srgb, var(--accent) 16%, var(--border));
    border-radius: 8px;
    background:
      linear-gradient(135deg, color-mix(in srgb, var(--accent) 12%, transparent), transparent 42%),
      color-mix(in srgb, var(--bg-secondary) 58%, transparent);
    box-shadow: var(--shadow-sm);
  }

  .pet-hero::before {
    content: '';
    position: absolute;
    inset: 10px;
    border: 1px solid color-mix(in srgb, var(--accent) 12%, transparent);
    border-radius: 8px;
    pointer-events: none;
  }

  .pet-hero-topline,
  .section-heading {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    position: relative;
    z-index: 1;
  }

  .eyebrow,
  .section-heading span {
    font-size: 10px;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--text-muted);
  }

  .section-heading strong {
    min-width: max-content;
    font-size: 11px;
    color: var(--text-secondary);
    font-weight: 700;
    text-transform: capitalize;
  }

  .status-pill {
    min-width: max-content;
    padding: 4px 8px;
    border-radius: 999px;
    font-size: 10px;
    font-weight: 800;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--accent);
    background: color-mix(in srgb, var(--accent) 12%, transparent);
    border: 1px solid color-mix(in srgb, var(--accent) 22%, transparent);
  }

  .status-pill[data-status="sleep"] {
    color: var(--text-muted);
    background: var(--bg-primary);
  }

  .status-pill[data-status="typing"] {
    color: #14b8a6;
    background: rgba(20, 184, 166, 0.1);
    border-color: rgba(20, 184, 166, 0.24);
  }

  .status-pill[data-status="commit"],
  .status-pill[data-status="happy"] {
    color: #22c55e;
    background: rgba(34, 197, 94, 0.1);
    border-color: rgba(34, 197, 94, 0.24);
  }

  .pet-stage-shell {
    position: relative;
    width: min(210px, 72cqw);
    min-height: clamp(146px, 42cqw, 184px);
    display: grid;
    justify-items: center;
    align-content: end;
    margin-top: 10px;
  }

  .pet-bubble {
    position: relative;
    z-index: 2;
    min-width: 144px;
    max-width: min(240px, 86cqw);
    padding: 9px 13px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--bg-secondary);
    color: var(--text-primary);
    box-shadow: var(--shadow-sm);
    font-size: 12px;
    font-weight: 500;
    line-height: 1.35;
    text-align: center;
  }

  .pet-avatar-stage {
    width: clamp(108px, 36cqw, 156px);
    height: clamp(108px, 36cqw, 156px);
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: 8px;
    border: 0;
    border-radius: 999px;
    background:
      radial-gradient(circle at 50% 62%, color-mix(in srgb, var(--accent) 14%, transparent), transparent 66%),
      color-mix(in srgb, var(--bg-primary) 76%, transparent);
    cursor: pointer;
    transition: transform 0.16s ease, background 0.16s ease;
    user-select: none;
  }

  .pet-avatar-stage:hover {
    transform: translateY(-2px);
    background:
      radial-gradient(circle at 50% 62%, color-mix(in srgb, var(--accent) 20%, transparent), transparent 66%),
      var(--bg-primary);
  }

  .pet-avatar-stage:focus-visible,
  .action-btn:focus-visible,
  .type-btn:focus-visible,
  .edit-btn:focus-visible,
  .action-btn-sm:focus-visible {
    outline: 2px solid var(--accent);
    outline-offset: 2px;
  }

  @keyframes sparkle-rise {
    0% { transform: translateY(0) scale(0.4); opacity: 0; }
    20% { opacity: 1; }
    100% { transform: translate(var(--sx, 0), -54px) scale(1.05); opacity: 0; }
  }

  .sparkle {
    position: absolute;
    z-index: 3;
    width: 8px;
    height: 8px;
    border-radius: 2px;
    background: var(--accent);
    box-shadow: 0 0 12px color-mix(in srgb, var(--accent) 55%, transparent);
    pointer-events: none;
    animation: sparkle-rise 1.2s ease-out forwards;
  }

  .s1 { --sx: -28px; left: 32%; top: 50%; }
  .s2 { --sx: 28px; left: 64%; top: 44%; animation-delay: 0.16s; }
  .s3 { --sx: 0; left: 50%; top: 36%; animation-delay: 0.28s; }

  .pet-identity {
    position: relative;
    z-index: 2;
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
    margin-top: 4px;
  }

  .name-display {
    display: flex;
    align-items: center;
    gap: 6px;
    min-width: 0;
  }

  .name-display h2 {
    margin: 0;
    color: var(--text-primary);
    font-size: clamp(17px, 5cqw, 24px);
    font-weight: 800;
    line-height: 1.1;
    overflow-wrap: anywhere;
  }

  .edit-btn {
    width: 26px;
    height: 26px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    border: 0;
    border-radius: 6px;
    background: transparent;
    color: var(--text-muted);
    cursor: pointer;
  }

  .edit-btn:hover {
    color: var(--accent);
    background: var(--bg-hover);
  }

  .rename-row {
    width: 100%;
    max-width: 300px;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 6px;
  }

  .rename-input {
    width: min(150px, 100%);
    min-height: 32px;
    padding: 6px 9px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--bg-primary);
    color: var(--text-primary);
    font-size: 12px;
    text-align: center;
    outline: none;
  }

  .rename-input:focus {
    border-color: var(--accent);
  }

  .action-btn-sm {
    min-height: 32px;
    padding: 6px 10px;
    border: 1px solid var(--border);
    border-radius: 6px;
    cursor: pointer;
    font-size: 11px;
  }

  .save-btn {
    background: var(--accent);
    border-color: var(--accent);
    color: white;
  }

  .cancel-btn {
    background: var(--bg-secondary);
    color: var(--text-secondary);
  }

  .type-badge {
    color: var(--accent);
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.04em;
    text-transform: uppercase;
  }

  .hero-metrics {
    width: 100%;
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 8px;
    margin-top: clamp(10px, 3cqw, 14px);
    position: relative;
    z-index: 1;
  }

  .metric-chip {
    min-width: 0;
    display: flex;
    flex-direction: column;
    gap: 2px;
    padding: clamp(8px, 2.4cqw, 10px);
    border: 1px solid var(--border-subtle);
    border-radius: 8px;
    background: color-mix(in srgb, var(--bg-primary) 74%, transparent);
  }

  .metric-label {
    color: var(--text-muted);
    font-size: 9px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
  }

  .metric-value {
    color: var(--text-primary);
    font-size: clamp(14px, 4cqw, 16px);
    font-weight: 800;
    font-variant-numeric: tabular-nums;
  }

  .progress-card,
  .care-card,
  .type-card,
  .stats-overview {
    display: flex;
    flex-direction: column;
    gap: 11px;
    padding: 13px;
  }

  .controls-grid {
    display: grid;
    grid-template-columns: minmax(0, 1fr);
    gap: 10px;
  }

  @container (min-width: 520px) {
    .controls-grid {
      grid-template-columns: minmax(0, 0.95fr) minmax(0, 1.05fr);
    }
  }

  .progress-container {
    width: 100%;
    height: 9px;
    overflow: hidden;
    border-radius: 99px;
    background: var(--bg-secondary);
  }

  .progress-bar {
    height: 100%;
    border-radius: 99px;
    background: linear-gradient(90deg, var(--accent), color-mix(in srgb, var(--accent) 62%, white));
    box-shadow: 0 0 14px color-mix(in srgb, var(--accent) 32%, transparent);
    transition: width 0.3s ease;
  }

  .stat-footer {
    margin: 0;
    color: var(--text-muted);
    font-size: 10.5px;
  }

  .care-buttons {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 8px;
  }

  .action-btn {
    min-width: 0;
    min-height: 64px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: space-between;
    gap: 7px;
    padding: 10px;
    border: 1px solid var(--border);
    border-radius: 8px;
    background: var(--bg-secondary);
    color: var(--text-primary);
    cursor: pointer;
    font-size: 11.5px;
    font-weight: 700;
    text-align: left;
    transition: transform 0.15s ease, border-color 0.15s ease, background 0.15s ease;
  }

  .action-btn:hover:not(:disabled) {
    transform: translateY(-1px);
    background: var(--bg-hover);
    border-color: var(--accent);
  }

  .action-btn small {
    color: var(--text-muted);
    font-size: 10px;
    font-weight: 600;
  }

  .btn-icon {
    width: 26px;
    height: 26px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 7px;
    color: var(--accent);
    background: color-mix(in srgb, var(--accent) 12%, transparent);
  }

  .action-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .feed-btn {
    background: color-mix(in srgb, var(--accent) 8%, var(--bg-secondary));
    border-color: color-mix(in srgb, var(--accent) 20%, transparent);
  }

  .type-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 7px;
  }

  .type-btn {
    min-width: 0;
    min-height: 58px;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
    gap: 3px;
    padding: 8px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--bg-primary);
    color: var(--text-muted);
    cursor: pointer;
    font-size: 11px;
    font-weight: 700;
    text-align: left;
    transition: all 0.12s;
  }

  .type-btn small {
    color: var(--text-muted);
    font-size: 9.5px;
    font-weight: 500;
    line-height: 1.2;
  }

  .type-btn:hover {
    color: var(--text-primary);
    background: var(--bg-hover);
  }

  .type-btn.active {
    border-color: color-mix(in srgb, var(--accent) 42%, var(--border));
    background: color-mix(in srgb, var(--accent) 10%, var(--bg-secondary));
    color: var(--accent);
  }

  .stats-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 8px;
    text-align: center;
  }

  .stat-item {
    min-width: 0;
    display: flex;
    flex-direction: column;
    padding: 10px 6px;
    border: 1px solid var(--border-subtle);
    border-radius: 6px;
    background: var(--bg-primary);
  }

  .stat-item .val {
    color: var(--text-primary);
    font-size: 15px;
    font-weight: 800;
    font-variant-numeric: tabular-nums;
  }

  .stat-item .lbl {
    margin-top: 2px;
    color: var(--text-muted);
    font-size: 9px;
  }

  /* Wide layout (Side-by-side) */
  @container (min-width: 500px) {
    .devpet-container {
      display: grid;
      grid-template-columns: 230px 1fr;
      align-items: start;
      gap: 12px;
    }

    .pet-hero {
      position: sticky;
      top: 0;
    }
  }

  /* Intermediate narrow layout settings */
  @container (max-width: 380px) {
    .devpet-container {
      gap: 8px;
    }

    .pet-hero {
      padding: 12px;
    }

    .pet-stage-shell {
      width: min(170px, 68cqw);
      min-height: 136px;
      margin-top: 8px;
    }

    .pet-bubble {
      min-width: 0;
      max-width: 100%;
      padding: 8px 10px;
      font-size: 11.5px;
    }

    .pet-avatar-stage {
      width: 112px;
      height: 112px;
    }

    .hero-metrics {
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 6px;
    }

    .metric-chip {
      padding: 7px 6px;
    }

    .metric-label {
      font-size: 8px;
      letter-spacing: 0.04em;
    }

    .metric-value {
      font-size: 13px;
    }
  }

  /* Compact details when narrow sidebar */
  @container (max-width: 320px) {
    .type-btn small {
      display: none;
    }
    
    .type-btn {
      min-height: 38px;
      align-items: center;
      justify-content: center;
      text-align: center;
    }
  }

  /* Extreme narrow layout */
  @container (max-width: 300px) {
    .pet-hero {
      padding: 10px;
    }

    .pet-stage-shell {
      width: 100%;
      min-height: 128px;
    }

    .section-heading,
    .pet-hero-topline {
      align-items: flex-start;
      flex-direction: column;
    }
  }

  @container (max-width: 260px) {
    .type-grid,
    .care-buttons,
    .stats-grid {
      grid-template-columns: 1fr;
    }

    .hero-metrics {
      grid-template-columns: 1fr;
    }
  }

  /* Height Responsiveness: Keep layout compact when vertical space is restricted */
  @container (max-height: 480px) {
    .devpet-container {
      gap: 6px;
      padding: clamp(6px, 2cqw, 10px);
    }

    .pet-hero {
      padding: clamp(8px, 2.5cqh, 14px);
    }

    .pet-stage-shell {
      min-height: clamp(80px, 22cqh, 110px);
      margin-top: 4px;
    }

    .pet-avatar-stage {
      width: clamp(70px, 20cqh, 96px);
      height: clamp(70px, 20cqh, 96px);
      margin-top: 4px;
    }

    .pet-bubble {
      font-size: 11px;
      padding: 5px 8px;
      min-width: 0;
      max-width: 95%;
    }

    .name-display h2 {
      font-size: 16px;
    }

    .hero-metrics {
      margin-top: 6px;
      gap: 4px;
    }

    .metric-chip {
      padding: 5px 4px;
    }

    .metric-value {
      font-size: 12px;
    }

    .progress-card,
    .care-card,
    .type-card,
    .stats-overview {
      padding: clamp(8px, 2cqh, 10px);
      gap: 6px;
    }

    .action-btn {
      min-height: 48px;
      padding: 6px;
      font-size: 11px;
      gap: 4px;
    }

    .btn-icon {
      width: 20px;
      height: 20px;
    }

    .type-btn {
      min-height: 42px;
      padding: 5px;
    }

    .stat-item {
      padding: 6px 4px;
    }

    .stat-item .val {
      font-size: 13px;
    }
  }

  @container (max-height: 360px) {
    .pet-stage-shell {
      min-height: clamp(50px, 18cqh, 70px);
    }

    .pet-avatar-stage {
      width: clamp(50px, 16cqh, 64px);
      height: clamp(50px, 16cqh, 64px);
    }

    .pet-bubble {
      display: none; /* Hide bubble text to save space when extremely short */
    }

    .hero-metrics {
      margin-top: 4px;
      gap: 4px;
    }
    
    .metric-chip {
      padding: 4px;
      border: none;
      background: transparent;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      gap: 4px;
    }
    
    .metric-label {
      font-size: 8px;
    }
    
    .metric-value {
      font-size: 11px;
    }
  }
</style>

// src/lib/components/pet/DevPetPanel.tsx
import { useMemo, useState } from 'react';
import { useStore } from '$lib/react/useStore';
import { devpet } from '$lib/stores/devpet';
import { showToast } from '$lib/stores/notification';
import PetAvatar from './PetAvatar.tsx';
import './DevPetPanel.css';

const companionTypes = [
  { id: 'cat' as const, label: 'Cat', desc: 'Warm and focused' },
  { id: 'slime' as const, label: 'Slime', desc: 'Soft and lively' },
  { id: 'robo' as const, label: 'Robo', desc: 'Sharp and precise' },
];

export default function DevPetPanel() {
  const pet = useStore(devpet);
  const [renameMode, setRenameMode] = useState(false);
  const [newName, setNewName] = useState('');

  const bubbleText = useMemo(() => {
    switch (pet.status) {
      case 'sleep':
        return 'zZz... recharging quietly.';
      case 'typing':
        return pet.wpm > 60 ? `Fast flow: ${pet.wpm} WPM.` : `Typing rhythm: ${pet.wpm} WPM.`;
      case 'commit':
        return 'Commit logged. Clean work.';
      case 'happy':
        return 'That hit the spot.';
      case 'eating':
        return 'Snack break accepted.';
      case 'idle':
      default:
        return 'Ready when you are.';
    }
  }, [pet.status, pet.wpm]);

  const xpDisplay = Math.round(pet.xp);
  const xpToNextDisplay = Math.round(pet.xpToNextLevel);
  const xpProgress = Math.max(0, Math.min(100, (pet.xp / Math.max(1, pet.xpToNextLevel)) * 100));
  const xpRemaining = Math.max(0, xpToNextDisplay - xpDisplay);

  function handleFeed() {
    if (pet.coins < 10) {
      showToast('Not enough coins. Write more code to earn coins.', 'warning');
      return;
    }
    const success = devpet.feed();
    if (success) {
      showToast(`${pet.name} enjoyed the snack. (+15 XP)`, 'success');
    }
  }

  function handlePet() {
    devpet.pet();
  }

  function startRename() {
    setNewName(pet.name);
    setRenameMode(true);
  }

  function saveRename() {
    const trimmed = newName.trim();
    if (!trimmed) return;
    devpet.rename(trimmed);
    setRenameMode(false);
    showToast(`Renamed companion to ${trimmed}.`, 'success');
  }

  function switchType(type: 'cat' | 'slime' | 'robo') {
    devpet.setType(type);
    showToast(`Switched companion to ${type}.`, 'info');
  }

  return (
    <div className="devpet-panel">
      <div className="devpet-container scrollable">
        <section className="pet-hero" aria-label="DevPet companion">
          <div className="pet-hero-topline">
            <span className="eyebrow">DevPet</span>
            <span className="status-pill" data-status={pet.status}>{pet.status}</span>
          </div>

          <div className="pet-stage-shell">
            <div className="pet-bubble" aria-live="polite">{bubbleText}</div>

            <button className="pet-avatar-stage" onClick={handlePet} title="Pet companion" aria-label={`Pet ${pet.name}`} style={{ pointerEvents: 'auto' }}>
              <div style={{ pointerEvents: 'none' }}>
                <PetAvatar type={pet.type} status={pet.status} skin={pet.skin} />
              </div>
            </button>

            {pet.status === 'happy' && (
              <>
                <span key="sparkle-1" className="sparkle s1"></span>
                <span key="sparkle-2" className="sparkle s2"></span>
                <span key="sparkle-3" className="sparkle s3"></span>
              </>
            )}
          </div>

          <div className="pet-identity">
            {renameMode ? (
              <div className="rename-row">
                <input
                  type="text"
                  className="rename-input"
                  value={newName}
                  onChange={(e) => setNewName(e.target.value)}
                  maxLength={16}
                  onKeyDown={(e) => e.key === 'Enter' && saveRename()}
                  aria-label="New companion name"
                />
                <button className="action-btn-sm save-btn" onClick={saveRename}>Save</button>
                <button className="action-btn-sm cancel-btn" onClick={() => setRenameMode(false)}>Cancel</button>
              </div>
            ) : (
              <div className="name-display">
                <h2>{pet.name}</h2>
                <button className="edit-btn" onClick={startRename} aria-label="Rename companion">
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M12 20h9" />
                    <path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z" />
                  </svg>
                </button>
              </div>
            )}
            <span className="type-badge">Level {pet.level} {pet.type}</span>
          </div>

          <div className="hero-metrics">
            <div className="metric-chip">
              <span className="metric-label">Coins</span>
              <span className="metric-value">{pet.coins}</span>
            </div>
            <div className="metric-chip">
              <span className="metric-label">WPM</span>
              <span className="metric-value">{pet.wpm}</span>
            </div>
            <div className="metric-chip">
              <span className="metric-label">XP</span>
              <span className="metric-value">{xpDisplay}</span>
            </div>
          </div>
        </section>

        <div className="devpet-aside">
          <section className="progress-card bento-card">
            <div className="section-heading">
              <span>Progress</span>
              <strong>{xpDisplay} / {xpToNextDisplay} XP</strong>
            </div>
            <div className="progress-container" aria-label="Experience progress">
              <div className="progress-bar" style={{ width: `${xpProgress}%` }}></div>
            </div>
            <p className="stat-footer">Need {xpRemaining} XP to level up</p>
          </section>

          <section className="controls-grid">
            <div className="bento-card care-card">
              <div className="section-heading">
                <span>Care</span>
                <strong>{pet.totalFeedCount} snacks</strong>
              </div>
              <div className="care-buttons">
                <button className="action-btn feed-btn" onClick={handleFeed} disabled={pet.coins < 10}>
                  <span className="btn-icon" aria-hidden="true">
                    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M4 11a8 8 0 0 1 16 0" />
                      <path d="M3 11h18" />
                      <path d="M5 15h14" />
                      <path d="M6 19h12" />
                    </svg>
                  </span>
                  <span>Feed snack</span>
                  <small>10 coins</small>
                </button>

                <button className="action-btn play-btn" onClick={handlePet}>
                  <span className="btn-icon" aria-hidden="true">
                    <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21.2l7.7-7.7 1.1-1.1a5.5 5.5 0 0 0 0-7.8Z" />
                    </svg>
                  </span>
                  <span>Pet companion</span>
                  <small>Free</small>
                </button>
              </div>
            </div>

            <div className="bento-card type-card">
              <div className="section-heading">
                <span>Companion</span>
                <strong>{pet.type}</strong>
              </div>
              <div className="type-grid">
                {companionTypes.map((option) => (
                  <button
                    key={option.id}
                    type="button"
                    className={`type-btn${pet.type === option.id ? ' active' : ''}`}
                    onClick={() => switchType(option.id)}
                  >
                    <span>{option.label}</span>
                    <small>{option.desc}</small>
                  </button>
                ))}
              </div>
            </div>
          </section>

          <section className="bento-card stats-overview">
            <div className="section-heading">
              <span>Workspace stats</span>
              <strong>Lifetime</strong>
            </div>
            <div className="stats-grid">
              <div className="stat-item">
                <span className="val">{pet.totalCharactersTyped.toLocaleString()}</span>
                <span className="lbl">Characters</span>
              </div>
              <div className="stat-item">
                <span className="val">{pet.totalCommits}</span>
                <span className="lbl">Commits</span>
              </div>
              <div className="stat-item">
                <span className="val">{pet.totalFeedCount}</span>
                <span className="lbl">Snacks</span>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
