// src/lib/components/workspace/FloatingNotepad.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import { loadScratchNote, saveScratchNote, closeFloatingNote } from '$lib/stores/notes';
import { activeProject } from '$lib/stores/workspace';
import { showToast } from '$lib/stores/notification';
import { createVoiceInputSession, mergeVoiceTranscript } from '$lib/services/voice-input';
import { refineVoicePrompt } from '$lib/services/voice-refinement';
import { useStore } from '$lib/react/useStore';
import './FloatingNotepad.css';

/** The eight resize directions: four edges + four corners. Each string encodes
 *  which edges of the window the drag moves (n/s/e/w). */
type ResizeDir = 'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw';

const NOTE_MIN_W = 260;
const NOTE_MIN_H = 180;

export default function FloatingNotepad() {
  const project = useStore(activeProject);

  const [posX, setPosX] = useState(() => window.innerWidth - 420);
  const [posY, setPosY] = useState(80);
  const [width, setWidth] = useState(380);
  const [height, setHeight] = useState(480);
  const [previewMode, setPreviewMode] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [resizing, setResizing] = useState(false);

  const [content, setContent] = useState('');
  const [saved, setSaved] = useState(true);
  const [isListening, setIsListening] = useState(false);
  const [isRefining, setIsRefining] = useState(false);

  const panelRef = useRef<HTMLDivElement | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  // Transient drag/resize bookkeeping — doesn't drive rendering, so refs avoid
  // extra re-renders on every mousemove.
  const dragStartX = useRef(0);
  const dragStartY = useRef(0);
  const dragOriginX = useRef(0);
  const dragOriginY = useRef(0);
  const resizeStartX = useRef(0);
  const resizeStartY = useRef(0);
  const resizeOriginW = useRef(0);
  const resizeOriginH = useRef(0);
  // The window's top-left at gesture start — needed because dragging the top or
  // left edge moves the anchor so the opposite edge stays put.
  const resizeOriginX = useRef(0);
  const resizeOriginY = useRef(0);
  const resizeDir = useRef<ResizeDir>('se');
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Mutable mirrors of state read inside stable callbacks (voice session,
  // mousemove/mouseup) so those closures always see the latest values
  // without needing to be recreated every render.
  const contentRef = useRef(content);
  contentRef.current = content;
  const widthRef = useRef(width);
  widthRef.current = width;
  const heightRef = useRef(height);
  heightRef.current = height;
  const draggingRef = useRef(dragging);
  draggingRef.current = dragging;
  const resizingRef = useRef(resizing);
  resizingRef.current = resizing;

  const voiceLocked = useRef(false);
  const voiceHeld = useRef(false);
  const voiceStopping = useRef(false);
  const voiceBaseContent = useRef('');
  const voiceDraftText = useRef('');

  const renderedHtml = useMemo(
    () => (previewMode ? (DOMPurify.sanitize(marked.parse(content) as string)) : ''),
    [previewMode, content]
  );

  function queueSave() {
    setSaved(false);
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(async () => {
      saveTimer.current = null;
      if (!project) { setSaved(true); return; }
      try {
        await saveScratchNote(project, contentRef.current);
        setSaved(true);
      } catch {
        // indicator stays unsaved — non-fatal
      }
    }, 400);
  }

  // Load from .soryq/scratch.md when project changes
  useEffect(() => {
    if (!project) { setContent(''); setSaved(true); return; }
    loadScratchNote(project).then(c => {
      setContent(c);
      setSaved(true);
      if (textareaRef.current) textareaRef.current.value = c;
    });
  }, [project]);

  function handleInput(e: React.ChangeEvent<HTMLTextAreaElement>) {
    setContent(e.target.value);
    queueSave();
  }

  const voiceInput = useMemo(() => createVoiceInputSession({
    onStart: () => {
      setIsListening(true);
      setIsRefining(false);
      voiceBaseContent.current = contentRef.current;
      voiceDraftText.current = '';
      showToast('Listening for notes...', 'info');
    },
    onResult: (transcript) => {
      voiceDraftText.current = transcript;
    },
    onEnd: () => {
      const shouldRestart = !voiceStopping.current && (voiceLocked.current || voiceHeld.current);
      setIsListening(false);
      setIsRefining(true);

      void (async () => {
        try {
          const { text: refinedTranscript } = await refineVoicePrompt(voiceDraftText.current);
          const merged = mergeVoiceTranscript(
            voiceBaseContent.current,
            refinedTranscript,
            voiceBaseContent.current.includes('\n') ? '\n' : ' '
          );
          setContent(merged);
          queueSave();
          requestAnimationFrame(() => textareaRef.current?.focus());
        } catch (error) {
          console.error('Failed to refine floating note voice input:', error);
        } finally {
          setIsRefining(false);
          voiceStopping.current = false;
          voiceBaseContent.current = '';
          voiceDraftText.current = '';
          if (shouldRestart) {
            queueMicrotask(() => {
              if (voiceLocked.current || voiceHeld.current) {
                voiceInput.start();
              }
            });
          }
        }
      })();
    },
    onError: (message) => {
      setIsListening(false);
      setIsRefining(false);
      voiceLocked.current = false;
      voiceHeld.current = false;
      voiceStopping.current = false;
      voiceBaseContent.current = '';
      voiceDraftText.current = '';
      showToast(message, 'error');
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }), []);

  async function toggleVoiceInput() {
    if (isRefining) return;
    if (isListening && voiceLocked.current) {
      voiceLocked.current = false;
      voiceStopping.current = true;
      voiceInput.stop();
      return;
    }
    voiceLocked.current = true;
    await voiceInput.start();
  }

  useEffect(() => {
    function handleGlobalVoiceShortcut(event: KeyboardEvent) {
      if (event.key !== 'Alt' || event.location !== KeyboardEvent.DOM_KEY_LOCATION_LEFT || event.repeat || isRefining) return;
      const activeElement = document.activeElement;
      if (!panelRef.current || !activeElement || !panelRef.current.contains(activeElement)) return;
      event.preventDefault();
      if (voiceLocked.current || voiceHeld.current) return;
      voiceHeld.current = true;
      voiceInput.start();
    }

    function handleGlobalVoiceShortcutUp(event: KeyboardEvent) {
      if (event.key !== 'Alt' || event.location !== KeyboardEvent.DOM_KEY_LOCATION_LEFT) return;
      if (!voiceHeld.current) return;
      voiceHeld.current = false;
      voiceStopping.current = true;
      voiceInput.stop();
    }

    document.addEventListener('keydown', handleGlobalVoiceShortcut);
    document.addEventListener('keyup', handleGlobalVoiceShortcutUp);
    return () => {
      document.removeEventListener('keydown', handleGlobalVoiceShortcut);
      document.removeEventListener('keyup', handleGlobalVoiceShortcutUp);
    };
  }, [isRefining, voiceInput]);

  function startDrag(e: React.MouseEvent) {
    if ((e.target as HTMLElement).closest('button')) return;
    setDragging(true);
    dragStartX.current = e.clientX; dragStartY.current = e.clientY;
    dragOriginX.current = posX; dragOriginY.current = posY;
    e.preventDefault();
  }

  function startResize(e: React.MouseEvent, dir: ResizeDir) {
    setResizing(true);
    resizeDir.current = dir;
    resizeStartX.current = e.clientX; resizeStartY.current = e.clientY;
    resizeOriginW.current = width; resizeOriginH.current = height;
    resizeOriginX.current = posX; resizeOriginY.current = posY;
    e.preventDefault();
    e.stopPropagation();
  }

  useEffect(() => {
    function onMouseMove(e: MouseEvent) {
      if (draggingRef.current) {
        setPosX(Math.max(0, Math.min(window.innerWidth - widthRef.current, dragOriginX.current + (e.clientX - dragStartX.current))));
        setPosY(Math.max(0, Math.min(window.innerHeight - 60, dragOriginY.current + (e.clientY - dragStartY.current))));
      }
      if (resizingRef.current) {
        const dir = resizeDir.current;
        const dx = e.clientX - resizeStartX.current;
        const dy = e.clientY - resizeStartY.current;
        const origX = resizeOriginX.current;
        const origY = resizeOriginY.current;
        const origW = resizeOriginW.current;
        const origH = resizeOriginH.current;

        // Right / bottom edges grow the box from its top-left anchor.
        if (dir.includes('e')) setWidth(Math.max(NOTE_MIN_W, origW + dx));
        if (dir.includes('s')) setHeight(Math.max(NOTE_MIN_H, origH + dy));
        // Left / top edges move the anchor too, so the opposite edge stays put.
        if (dir.includes('w')) {
          const w = Math.max(NOTE_MIN_W, origW - dx);
          setWidth(w);
          setPosX(origX + (origW - w));
        }
        if (dir.includes('n')) {
          const h = Math.max(NOTE_MIN_H, origH - dy);
          setHeight(h);
          setPosY(origY + (origH - h));
        }
      }
    }

    function onMouseUp() {
      setDragging(false);
      setResizing(false);
    }

    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
    return () => {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    };
  }, []);

  useEffect(() => {
    return () => {
      if (saveTimer.current) clearTimeout(saveTimer.current);
    };
  }, []);

  return (
    <div
      ref={panelRef}
      className="floating-notepad"
      style={{ left: `${posX}px`, top: `${posY}px`, width: `${width}px`, height: `${height}px` }}
    >
      <div className="note-header" onMouseDown={startDrag} role="presentation">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="drag-icon">
          <circle cx="9" cy="6" r="1.5" fill="currentColor"/><circle cx="15" cy="6" r="1.5" fill="currentColor"/>
          <circle cx="9" cy="12" r="1.5" fill="currentColor"/><circle cx="15" cy="12" r="1.5" fill="currentColor"/>
          <circle cx="9" cy="18" r="1.5" fill="currentColor"/><circle cx="15" cy="18" r="1.5" fill="currentColor"/>
        </svg>
        <span className="note-title">Notes{project ? ` - ${project.name}` : ''}</span>
        <div className="note-actions">
          <button
            className={`note-action-btn${isListening ? ' listening' : ''}${isRefining ? ' refining' : ''}`}
            onClick={toggleVoiceInput}
            title={isListening ? 'Stop listening' : isRefining ? 'Refining with AI…' : 'Start voice input'}
            aria-label={isListening ? 'Stop listening' : isRefining ? 'Refining with AI…' : 'Start voice input'}
            disabled={isRefining}
          >
            {isRefining ? (
              <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="spin-icon">
                <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/>
              </svg>
            ) : (
              <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.3" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/>
                <path d="M19 10v1a7 7 0 0 1-14 0v-1"/>
                <line x1="12" x2="12" y1="19" y2="22"/>
              </svg>
            )}
          </button>
          {isRefining ? (
            <span className="refining-label">Refining…</span>
          ) : (
            <span className={`save-indicator${saved ? ' saved' : ''}`}>
              {saved ? 'Saved' : 'Saving...'}
            </span>
          )}
          <button
            className={`note-action-btn${previewMode ? ' active' : ''}`}
            onClick={() => setPreviewMode(v => !v)}
            title={previewMode ? 'Edit mode' : 'Preview markdown'}
          >MD</button>
          <button className="note-action-btn note-close-btn" onClick={closeFloatingNote} title="Close">
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
              <path d="M18 6L6 18M6 6l12 12"/>
            </svg>
          </button>
        </div>
      </div>

      <div className="note-body">
        {previewMode ? (
          <div className="note-preview markdown-body" dangerouslySetInnerHTML={{ __html: renderedHtml }} />
        ) : (
          <textarea
            ref={textareaRef}
            className="note-textarea"
            value={content}
            onChange={handleInput}
            placeholder="Write notes in markdown… saved to .soryq/scratch.md"
            spellCheck={false}
          ></textarea>
        )}
      </div>

      {/* Eight resize handles — four edges and four corners — so the notepad can
          be grabbed from any side or angle. */}
      {(['n', 's', 'e', 'w', 'ne', 'nw', 'se', 'sw'] as ResizeDir[]).map((dir) => (
        <div
          key={dir}
          className={`note-resize note-resize-${dir}`}
          onMouseDown={(e) => startResize(e, dir)}
          role="presentation"
        ></div>
      ))}
    </div>
  );
}

// src/lib/components/workspace/FloatingNotepad.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { marked } from 'marked';
  import DOMPurify from 'dompurify';
  import { loadScratchNote, saveScratchNote, closeFloatingNote } from '$lib/stores/notes';
  import { activeProject } from '$lib/stores/workspace';
  import { showToast } from '$lib/stores/notification';
  import { createVoiceInputSession, mergeVoiceTranscript } from '$lib/services/voice-input';
  import { refineVoicePrompt } from '$lib/services/voice-refinement';

  let posX = $state(window.innerWidth - 420);
  let posY = $state(80);
  let width = $state(380);
  let height = $state(480);
  let previewMode = $state(false);
  let dragging = $state(false);
  let resizing = $state(false);
  let dragStartX = 0, dragStartY = 0, dragOriginX = 0, dragOriginY = 0;
  let resizeStartX = 0, resizeStartY = 0, resizeOriginW = 0, resizeOriginH = 0;
  let saveTimer: ReturnType<typeof setTimeout> | null = null;

  let content = $state('');
  let saved = $state(true);
  let panelEl = $state<HTMLDivElement | null>(null);
  let textareaEl = $state<HTMLTextAreaElement | null>(null);
  let isListening = $state(false);
  let isRefining = $state(false);
  let voiceLocked = $state(false);
  let voiceHeld = $state(false);
  let voiceStopping = $state(false);
  let voiceBaseContent = $state('');
  let voiceDraftText = $state('');
  let renderedHtml = $derived(
    previewMode ? DOMPurify.sanitize(marked.parse(content) as string) : ''
  );

  function queueSave() {
    saved = false;
    if (saveTimer) clearTimeout(saveTimer);
    saveTimer = setTimeout(async () => {
      saveTimer = null;
      const project = $activeProject;
      if (!project) { saved = true; return; }
      try {
        await saveScratchNote(project, content);
        saved = true;
      } catch {
        // indicator stays unsaved — non-fatal
      }
    }, 400);
  }

  // Load from .soryq/scratch.md when project changes
  $effect(() => {
    const project = $activeProject;
    if (!project) { content = ''; saved = true; return; }
    loadScratchNote(project).then(c => {
      content = c;
      saved = true;
      if (textareaEl) textareaEl.value = c;
    });
  });

  function handleInput(e: Event) {
    content = (e.target as HTMLTextAreaElement).value;
    queueSave();
  }

  const voiceInput = createVoiceInputSession({
    onStart: () => {
      isListening = true;
      isRefining = false;
      voiceBaseContent = content;
      voiceDraftText = '';
      showToast('Listening for notes...', 'info');
    },
    onResult: (transcript) => {
      voiceDraftText = transcript;
    },
    onEnd: () => {
      const shouldRestart = !voiceStopping && (voiceLocked || voiceHeld);
      isListening = false;
      isRefining = true;

      void (async () => {
        try {
          const { text: refinedTranscript } = await refineVoicePrompt(voiceDraftText);
          content = mergeVoiceTranscript(
            voiceBaseContent,
            refinedTranscript,
            voiceBaseContent.includes('\n') ? '\n' : ' '
          );
          queueSave();
          requestAnimationFrame(() => textareaEl?.focus());
        } catch (error) {
          console.error('Failed to refine floating note voice input:', error);
        } finally {
          isRefining = false;
          voiceStopping = false;
          voiceBaseContent = '';
          voiceDraftText = '';
          if (shouldRestart) {
            queueMicrotask(() => {
              if (voiceLocked || voiceHeld) {
                voiceInput.start();
              }
            });
          }
        }
      })();
    },
    onError: (message) => {
      isListening = false;
      isRefining = false;
      voiceLocked = false;
      voiceHeld = false;
      voiceStopping = false;
      voiceBaseContent = '';
      voiceDraftText = '';
      showToast(message, 'error');
    },
  });

  async function toggleVoiceInput() {
    if (isRefining) return;
    if (isListening && voiceLocked) {
      voiceLocked = false;
      voiceStopping = true;
      voiceInput.stop();
      return;
    }
    voiceLocked = true;
    await voiceInput.start();
  }

  function handleGlobalVoiceShortcut(event: KeyboardEvent) {
    if (event.key !== 'Alt' || event.location !== KeyboardEvent.DOM_KEY_LOCATION_LEFT || event.repeat || isRefining) return;
    const activeElement = document.activeElement;
    if (!panelEl || !activeElement || !panelEl.contains(activeElement)) return;
    event.preventDefault();
    if (voiceLocked || voiceHeld) return;
    voiceHeld = true;
    voiceInput.start();
  }

  function handleGlobalVoiceShortcutUp(event: KeyboardEvent) {
    if (event.key !== 'Alt' || event.location !== KeyboardEvent.DOM_KEY_LOCATION_LEFT) return;
    if (!voiceHeld) return;
    voiceHeld = false;
    voiceStopping = true;
    voiceInput.stop();
  }

  function startDrag(e: MouseEvent) {
    if ((e.target as HTMLElement).closest('button')) return;
    dragging = true;
    dragStartX = e.clientX; dragStartY = e.clientY;
    dragOriginX = posX; dragOriginY = posY;
    e.preventDefault();
  }

  function startResize(e: MouseEvent) {
    resizing = true;
    resizeStartX = e.clientX; resizeStartY = e.clientY;
    resizeOriginW = width; resizeOriginH = height;
    e.preventDefault();
    e.stopPropagation();
  }

  function onMouseMove(e: MouseEvent) {
    if (dragging) {
      posX = Math.max(0, Math.min(window.innerWidth - width, dragOriginX + (e.clientX - dragStartX)));
      posY = Math.max(0, Math.min(window.innerHeight - 60, dragOriginY + (e.clientY - dragStartY)));
    }
    if (resizing) {
      width = Math.max(260, resizeOriginW + (e.clientX - resizeStartX));
      height = Math.max(180, resizeOriginH + (e.clientY - resizeStartY));
    }
  }

  function onMouseUp() {
    dragging = false;
    resizing = false;
  }

  onMount(() => {
    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
    document.addEventListener('keydown', handleGlobalVoiceShortcut);
    document.addEventListener('keyup', handleGlobalVoiceShortcutUp);
  });

  onDestroy(() => {
    document.removeEventListener('mousemove', onMouseMove);
    document.removeEventListener('mouseup', onMouseUp);
    document.removeEventListener('keydown', handleGlobalVoiceShortcut);
    document.removeEventListener('keyup', handleGlobalVoiceShortcutUp);
    if (saveTimer) clearTimeout(saveTimer);
  });
</script>

<div
  bind:this={panelEl}
  class="floating-notepad"
  style="left: {posX}px; top: {posY}px; width: {width}px; height: {height}px;"
>
  <div class="note-header" onmousedown={startDrag} role="presentation">
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" class="drag-icon">
      <circle cx="9" cy="6" r="1.5" fill="currentColor"/><circle cx="15" cy="6" r="1.5" fill="currentColor"/>
      <circle cx="9" cy="12" r="1.5" fill="currentColor"/><circle cx="15" cy="12" r="1.5" fill="currentColor"/>
      <circle cx="9" cy="18" r="1.5" fill="currentColor"/><circle cx="15" cy="18" r="1.5" fill="currentColor"/>
    </svg>
    <span class="note-title">Notes{$activeProject ? ` - ${$activeProject.name}` : ''}</span>
    <div class="note-actions">
      <button
        class="note-action-btn"
        class:listening={isListening}
        class:refining={isRefining}
        onclick={toggleVoiceInput}
        title={isListening ? 'Stop listening' : isRefining ? 'Refining with AI…' : 'Start voice input'}
        aria-label={isListening ? 'Stop listening' : isRefining ? 'Refining with AI…' : 'Start voice input'}
        disabled={isRefining}
      >
        {#if isRefining}
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="spin-icon">
            <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/>
          </svg>
        {:else}
          <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/>
            <path d="M19 10v1a7 7 0 0 1-14 0v-1"/>
            <line x1="12" x2="12" y1="19" y2="22"/>
          </svg>
        {/if}
      </button>
      {#if isRefining}
        <span class="refining-label">Refining…</span>
      {:else}
        <span class="save-indicator" class:saved>
          {saved ? 'Saved' : 'Saving...'}
        </span>
      {/if}
      <button
        class="note-action-btn"
        class:active={previewMode}
        onclick={() => previewMode = !previewMode}
        title={previewMode ? 'Edit mode' : 'Preview markdown'}
      >MD</button>
      <button class="note-action-btn note-close-btn" onclick={closeFloatingNote} title="Close">
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round">
          <path d="M18 6L6 18M6 6l12 12"/>
        </svg>
      </button>
    </div>
  </div>

  <div class="note-body">
    {#if previewMode}
      <div class="note-preview markdown-body">{@html renderedHtml}</div>
    {:else}
      <textarea
        bind:this={textareaEl}
        class="note-textarea"
        value={content}
        oninput={handleInput}
        placeholder="Write notes in markdown… saved to .soryq/scratch.md"
        spellcheck="false"
      ></textarea>
    {/if}
  </div>

  <div class="resize-handle" onmousedown={startResize} role="presentation"></div>
</div>

<style>
  .floating-notepad {
    position: fixed;
    z-index: 9000;
    background: var(--bg-secondary);
    border: 1px solid var(--border);
    border-radius: 10px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.4);
    display: flex;
    flex-direction: column;
    overflow: hidden;
    min-width: 260px;
    min-height: 180px;
  }

  .note-header {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 10px;
    background: var(--bg-tertiary, var(--bg-secondary));
    border-bottom: 1px solid var(--border);
    cursor: move;
    user-select: none;
    flex-shrink: 0;
  }

  .drag-icon {
    color: var(--text-muted);
    opacity: 0.4;
    flex-shrink: 0;
  }

  .note-title {
    flex: 1;
    font-size: 11.5px;
    font-weight: 600;
    color: var(--text-secondary);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .note-actions {
    display: flex;
    align-items: center;
    gap: 4px;
  }

  .save-indicator {
    font-size: 10px;
    color: var(--text-muted);
    opacity: 0.55;
    transition: color 0.2s, opacity 0.2s;
  }

  .save-indicator.saved {
    color: var(--success);
    opacity: 0.85;
  }

  .note-action-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 10px;
    font-weight: 600;
    background: transparent;
    border: 1px solid var(--border);
    color: var(--text-muted);
    cursor: pointer;
    transition: background 0.15s, color 0.15s, border-color 0.15s;
    line-height: 1.4;
  }

  .note-action-btn:hover {
    background: var(--bg-hover);
    color: var(--text-secondary);
  }

  .note-action-btn.active {
    background: var(--accent);
    color: #fff;
    border-color: var(--accent);
  }

  .note-action-btn.listening {
    background: rgba(239, 68, 68, 0.14);
    color: var(--error);
    border-color: rgba(239, 68, 68, 0.28);
  }

  .note-action-btn.refining {
    background: rgba(139, 92, 246, 0.14);
    color: #a78bfa;
    border-color: rgba(139, 92, 246, 0.35);
    cursor: default;
    animation: refine-glow 1.4s ease-in-out infinite;
  }

  .spin-icon {
    animation: sparkle-spin 1.6s linear infinite;
  }

  @keyframes sparkle-spin {
    0%   { transform: rotate(0deg) scale(1);     opacity: 1; }
    50%  { transform: rotate(180deg) scale(1.15); opacity: 0.7; }
    100% { transform: rotate(360deg) scale(1);   opacity: 1; }
  }

  @keyframes refine-glow {
    0%, 100% { box-shadow: 0 0 0 0 rgba(139, 92, 246, 0); }
    50%       { box-shadow: 0 0 6px 2px rgba(139, 92, 246, 0.25); }
  }

  .refining-label {
    font-size: 10px;
    color: #a78bfa;
    animation: refine-fade 1.2s ease-in-out infinite;
    white-space: nowrap;
  }

  @keyframes refine-fade {
    0%, 100% { opacity: 0.5; }
    50%       { opacity: 1; }
  }

  .note-close-btn:hover {
    background: var(--error, #e53e3e);
    color: #fff;
    border-color: var(--error, #e53e3e);
  }

  .note-body {
    flex: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    min-height: 0;
  }

  .note-textarea {
    flex: 1;
    width: 100%;
    background: transparent;
    border: none;
    outline: none;
    padding: 12px;
    color: var(--text-primary);
    font-family: var(--font-mono, monospace);
    font-size: 12.5px;
    line-height: 1.6;
    resize: none;
    box-sizing: border-box;
  }

  .note-textarea::placeholder {
    color: var(--text-muted);
    opacity: 0.6;
  }

  .note-preview {
    flex: 1;
    overflow-y: auto;
    padding: 12px;
    font-size: 12.5px;
    line-height: 1.6;
    color: var(--text-primary);
    box-sizing: border-box;
    scrollbar-width: thin;
  }

  .note-preview :global(h1),
  .note-preview :global(h2),
  .note-preview :global(h3),
  .note-preview :global(h4),
  .note-preview :global(h5),
  .note-preview :global(h6) {
    font-weight: 600;
    margin: 0.6em 0 0.3em;
    color: var(--text-primary);
    line-height: 1.3;
  }

  .note-preview :global(h1) { font-size: 1.3em; }
  .note-preview :global(h2) { font-size: 1.15em; }
  .note-preview :global(h3) { font-size: 1.05em; }
  .note-preview :global(p) { margin: 0.4em 0; }
  .note-preview :global(ul),
  .note-preview :global(ol) {
    margin: 0.4em 0;
    padding-left: 1.4em;
  }
  .note-preview :global(li) { margin: 0.15em 0; }
  .note-preview :global(code) {
    font-family: var(--font-mono, monospace);
    font-size: 0.9em;
    background: var(--bg-tertiary, rgba(255,255,255,0.07));
    border: 1px solid var(--border);
    border-radius: 3px;
    padding: 0.1em 0.35em;
    color: var(--accent);
  }
  .note-preview :global(pre) {
    background: var(--bg-tertiary, rgba(255,255,255,0.07));
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 10px 12px;
    overflow-x: auto;
    margin: 0.5em 0;
  }
  .note-preview :global(pre code) {
    background: none;
    border: none;
    padding: 0;
    color: var(--text-primary);
    font-size: 1em;
  }
  .note-preview :global(blockquote) {
    margin: 0.5em 0;
    padding: 4px 12px;
    border-left: 3px solid var(--accent);
    color: var(--text-secondary);
    font-style: italic;
  }
  .note-preview :global(a) {
    color: var(--accent);
    text-decoration: underline;
    text-underline-offset: 2px;
  }
  .note-preview :global(hr) {
    border: none;
    border-top: 1px solid var(--border);
    margin: 0.8em 0;
  }
  .note-preview :global(strong) { font-weight: 700; }
  .note-preview :global(em) { font-style: italic; }

  .resize-handle {
    position: absolute;
    bottom: 0;
    right: 0;
    width: 14px;
    height: 14px;
    cursor: nwse-resize;
    opacity: 0.4;
  }

  .resize-handle::after {
    content: '';
    position: absolute;
    bottom: 3px;
    right: 3px;
    width: 6px;
    height: 6px;
    border-right: 2px solid var(--text-muted);
    border-bottom: 2px solid var(--text-muted);
    border-radius: 0 0 2px 0;
  }

  .resize-handle:hover {
    opacity: 0.8;
  }
</style>
