// src/lib/components/workspace/TasksPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for TasksPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const TasksPanel = lazy(() => import('./TasksPanel.tsx'));

export default function TasksPanelLazy() {
  return (
    <Suspense fallback={null}>
      <TasksPanel />
    </Suspense>
  );
}

// src/lib/components/workspace/TasksPanelLazy.svelte
<!--
  Lazy boundary for TasksPanel — see EditorPanelLazy for the rationale. Loaded on
  demand; rendered in place of TasksPanel so call sites stay unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./TasksPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}
