// src/lib/components/containers/ContainersPanelLazy.svelte
<!--
  Lazy boundary for ContainersPanel — see EditorPanelLazy for the rationale.
  Loaded on demand; rendered in place of ContainersPanel so call sites stay
  unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./ContainersPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}

// src/lib/components/containers/ContainersPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for ContainersPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const ContainersPanel = lazy(() => import('./ContainersPanel.tsx'));

export default function ContainersPanelLazy() {
  return (
    <Suspense fallback={null}>
      <ContainersPanel />
    </Suspense>
  );
}
