// src/lib/components/db/DbExplorerPanelLazy.svelte
<!--
  Lazy boundary for DbExplorerPanel — see EditorPanelLazy for the rationale.
  Loaded on demand; rendered in place of DbExplorerPanel so call sites stay
  unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./DbExplorerPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}

// src/lib/components/db/DbExplorerPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for DbExplorerPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const DbExplorerPanel = lazy(() => import('./DbExplorerPanel.tsx'));

export default function DbExplorerPanelLazy() {
  return (
    <Suspense fallback={null}>
      <DbExplorerPanel />
    </Suspense>
  );
}
