// src/App.tsx
import { useEffect, lazy, Suspense } from 'react';
import { get } from '$lib/stores/storeCompat';
import { getCurrentWindow } from '@tauri-apps/api/window';
import AppShell from '$lib/components/layout/AppShell.tsx';
import BackgroundMedia from '$lib/components/shared/BackgroundMedia.tsx';
import CommandPalette from '$lib/components/shared/CommandPalette.tsx';
import Toasts from '$lib/components/shared/Toasts.tsx';
import QuickCaptureModal from '$lib/components/shared/QuickCaptureModal.tsx';
import WorkspaceNameModal from '$lib/components/shared/WorkspaceNameModal.tsx';
import MicrophonePermissionDialog from '$lib/components/shared/MicrophonePermissionDialog.tsx';
import SettingsModal from '$lib/components/shared/SettingsModal.tsx';
import { useStore } from '$lib/react/useStore';
import {
  settingsOpen,
  closeSettings,
  quickCaptureOpen,
  closeQuickCapture,
  envManagerOpen,
} from '$lib/stores/layout';
import {
  newWorkspacePromptOpen,
  initializeWorkspaces,
  saveProjectState,
  activeProjectId,
  activeProject,
} from '$lib/stores/workspace';
import { usePermissionsStore } from '$lib/stores/zustand/permissions';
import { openDailyNote } from '$lib/stores/dailyNote';
import { loadThemes } from '$lib/stores/theme';
import { initDefaultCommands } from '$lib/stores/commandpalette';
import { requestNotificationPermission } from '$lib/stores/notification';
import {
  uiZoom,
  userShortcuts,
  matchShortcut,
  type KeyboardShortcut,
  onboardingCompleted,
  reconcileOnboardingFlag,
  backgroundImageEnabled,
  interfaceTransparency,
  backgroundImageOpacity,
  backgroundImageBlur,
  closeBehavior,
} from '$lib/stores/settings';
import {
  initBackground,
  applyBackgroundImage,
  applyInterfaceFrost,
  applyBackgroundAppearance,
} from '$lib/stores/background';
import { initNavigationHistory } from '$lib/stores/navigation';
import { initApiKeyCache } from '$lib/services/ai-keychain';
import { isTauriRuntime } from '$lib/utils/tauri';

const ZOOM_LEVELS = [50, 67, 75, 80, 90, 100, 110, 125, 150, 175, 200] as const;

const EnvManager = lazy(() => import('$lib/components/shared/EnvManager.tsx'));
const OnboardingWalkthrough = lazy(() => import('$lib/components/workspace/OnboardingWalkthrough.tsx'));

function zoomIn() {
  uiZoom.update((z) => {
    const next = ZOOM_LEVELS.find((level) => level > z);
    return next ?? z;
  });
}

function zoomOut() {
  uiZoom.update((z) => {
    const next = [...ZOOM_LEVELS].reverse().find((level) => level < z);
    return next ?? z;
  });
}

export default function App() {
  const isSettingsOpen = useStore(settingsOpen);
  const isQuickCaptureOpen = useStore(quickCaptureOpen);
  const isEnvManagerOpen = useStore(envManagerOpen);
  const isNewWorkspacePromptOpen = useStore(newWorkspacePromptOpen);
  const permissionRequest = usePermissionsStore((s) => s.pendingPermissionRequest);
  const hasCompletedOnboarding = useStore(onboardingCompleted);

  useEffect(() => {
    if (isTauriRuntime()) {
      initApiKeyCache();
      loadThemes();
      initBackground();
      reconcileOnboardingFlag();
    }

    initializeWorkspaces();
    initDefaultCommands();
    if (isTauriRuntime()) {
      requestNotificationPermission();
    }
    initNavigationHistory();

    const unsubFrost = interfaceTransparency.subscribe((value) => {
      applyInterfaceFrost(value);
    });

    const unsubBgEnabled = backgroundImageEnabled.subscribe(() => applyBackgroundImage());

    let bgAppearanceRuns = 0;
    const applyAppearanceLive = () => {
      if (bgAppearanceRuns < 2) {
        bgAppearanceRuns += 1;
        return;
      }
      applyBackgroundAppearance(get(backgroundImageOpacity), get(backgroundImageBlur));
    };
    const unsubBgOpacity = backgroundImageOpacity.subscribe(applyAppearanceLive);
    const unsubBgBlur = backgroundImageBlur.subscribe(applyAppearanceLive);

    let lastDailyProjectId: string | null = null;
    const unsubDailyNote = activeProject.subscribe((project) => {
      if (project && project.id !== lastDailyProjectId) {
        lastDailyProjectId = project.id;
        openDailyNote(project).catch(() => {});
      }
    });

    let unlistenClose: (() => void) | undefined;
    if (isTauriRuntime()) {
      const win = getCurrentWindow();
      win
        .onCloseRequested(async (event) => {
          const projectId = get(activeProjectId);
          if (projectId) saveProjectState(projectId);

          if (get(closeBehavior) === 'minimize') {
            event.preventDefault();
            await win.minimize();
          }
        })
        .then((unlisten) => {
          unlistenClose = unlisten;
        });
    }

    const handleScroll = () => {
      if (window.scrollX !== 0 || window.scrollY !== 0) {
        window.scrollTo(0, 0);
      }
    };
    window.addEventListener('scroll', handleScroll, { passive: true });

    const unsubscribeZoom = uiZoom.subscribe((zoom) => {
      document.documentElement.style.setProperty('--ui-zoom-percent', `${zoom}`);
    });

    let activeShortcuts: KeyboardShortcut[] = [];
    const unsubscribeShortcuts = userShortcuts.subscribe((value) => {
      activeShortcuts = value || [];
    });

    const handleKeyDown = (event: KeyboardEvent) => {
      const zoomInShortcut = activeShortcuts.find((shortcut) => shortcut?.id === 'zoomIn');
      const zoomOutShortcut = activeShortcuts.find((shortcut) => shortcut?.id === 'zoomOut');
      const resetZoomShortcut = activeShortcuts.find((shortcut) => shortcut?.id === 'resetZoom');

      if (zoomInShortcut && matchShortcut(event, zoomInShortcut.keys)) {
        event.preventDefault();
        zoomIn();
      } else if (zoomOutShortcut && matchShortcut(event, zoomOutShortcut.keys)) {
        event.preventDefault();
        zoomOut();
      } else if (resetZoomShortcut && matchShortcut(event, resetZoomShortcut.keys)) {
        event.preventDefault();
        uiZoom.set(100);
      }
    };
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('keydown', handleKeyDown);
      unsubscribeZoom();
      unlistenClose?.();
      unsubscribeShortcuts();
      unsubDailyNote();
      unsubFrost();
      unsubBgEnabled();
      unsubBgOpacity();
      unsubBgBlur();
    };
  }, []);

  return (
    <>
      <BackgroundMedia />
      <AppShell />

      <CommandPalette />
      <Toasts />

      {isSettingsOpen && <SettingsModal onclose={closeSettings} />}

      {isQuickCaptureOpen && <QuickCaptureModal onclose={closeQuickCapture} />}

      {isEnvManagerOpen && (
        <Suspense fallback={null}>
          <EnvManager />
        </Suspense>
      )}

      {isNewWorkspacePromptOpen && <WorkspaceNameModal />}

      {!hasCompletedOnboarding && (
        <Suspense fallback={null}>
          <OnboardingWalkthrough />
        </Suspense>
      )}

      {permissionRequest && <MicrophonePermissionDialog />}
    </>
  );
}

// src/App.svelte
<script lang="ts">
  import AppShell from '$lib/components/layout/AppShell.svelte';
  import CommandPalette from '$lib/components/shared/CommandPalette.svelte';
  import Toasts from '$lib/components/shared/Toasts.svelte';
  import BackgroundMedia from '$lib/components/shared/BackgroundMedia.svelte';
  import SettingsModal from '$lib/components/shared/SettingsModal.svelte';
  import QuickCaptureModal from '$lib/components/shared/QuickCaptureModal.svelte';
  import WorkspaceNameModal from '$lib/components/shared/WorkspaceNameModal.svelte';
  import EnvManager from '$lib/components/shared/EnvManager.svelte';
  import { settingsOpen, closeSettings, quickCaptureOpen, closeQuickCapture, envManagerOpen } from '$lib/stores/layout';
  import { newWorkspacePromptOpen } from '$lib/stores/workspace';
  import MicrophonePermissionDialog from '$lib/components/shared/MicrophonePermissionDialog.svelte';
  import { pendingPermissionRequest } from '$lib/stores/permissions';
  import { onMount } from 'svelte';
  import { loadThemes } from '$lib/stores/theme';
  import { initializeWorkspaces, saveProjectState, activeProjectId, activeProject } from '$lib/stores/workspace';
  import { openDailyNote } from '$lib/stores/dailyNote';
  import { get } from 'svelte/store';
  import { getCurrentWindow } from '@tauri-apps/api/window';
  import { initDefaultCommands } from '$lib/stores/commandpalette';
  import { requestNotificationPermission } from '$lib/stores/notification';
  import { uiZoom, userShortcuts, matchShortcut, type KeyboardShortcut, onboardingCompleted, backgroundImageEnabled, interfaceTransparency, backgroundImageOpacity, backgroundImageBlur, closeBehavior } from '$lib/stores/settings';
  import { initBackground, applyBackgroundImage, applyInterfaceFrost, applyBackgroundAppearance } from '$lib/stores/background';
  import OnboardingWalkthrough from '$lib/components/workspace/OnboardingWalkthrough.svelte';
  import { initNavigationHistory } from '$lib/stores/navigation';
  import { initApiKeyCache } from '$lib/services/ai-keychain';
  import { isTauriRuntime } from '$lib/utils/tauri';

  const ZOOM_LEVELS = [50, 67, 75, 80, 90, 100, 110, 125, 150, 175, 200] as const;

  function zoomIn() {
    uiZoom.update(z => {
      const next = ZOOM_LEVELS.find(l => l > z);
      return next ?? z;
    });
  }

  function zoomOut() {
    uiZoom.update(z => {
      const next = [...ZOOM_LEVELS].reverse().find(l => l < z);
      return next ?? z;
    });
  }

  onMount(() => {
    if (isTauriRuntime()) {
      initApiKeyCache();
      loadThemes();
      initBackground();
    }
    initializeWorkspaces();
    initDefaultCommands();
    if (isTauriRuntime()) {
      requestNotificationPermission();
    }
    initNavigationHistory();

    // Live-apply the global interface transparency as the slider moves, and the
    // image layer when toggled. Skip the initial synchronous fire — startup is
    // handled by initBackground().
    let bgFirstRun = true;
    const unsubFrost = interfaceTransparency.subscribe((v) => {
      if (bgFirstRun) { bgFirstRun = false; return; }
      applyInterfaceFrost(v);
    });
    const unsubBgEnabled = backgroundImageEnabled.subscribe(() => applyBackgroundImage());
    // Live-apply background image opacity/blur as their sliders move (initial
    // values are applied by initBackground()).
    let bgAppearanceRuns = 0;
    const applyAppearanceLive = () => {
      // Skip the two initial synchronous fires (one per store subscription).
      if (bgAppearanceRuns < 2) { bgAppearanceRuns++; return; }
      applyBackgroundAppearance(get(backgroundImageOpacity), get(backgroundImageBlur));
    };
    const unsubBgOpacity = backgroundImageOpacity.subscribe(applyAppearanceLive);
    const unsubBgBlur = backgroundImageBlur.subscribe(applyAppearanceLive);

    // Auto-open today's daily note once per project per day
    let lastDailyProjectId: string | null = null;
    const unsubDailyNote = activeProject.subscribe((project) => {
      if (project && project.id !== lastDailyProjectId) {
        lastDailyProjectId = project.id;
        openDailyNote(project).catch(() => {});
      }
    });

    // Save project state before the window closes — use Tauri's close-request hook
    // which fires reliably on all platforms (beforeunload is unreliable on macOS/Tauri).
    let unlistenClose: (() => void) | undefined;
    if (isTauriRuntime()) {
      const win = getCurrentWindow();
      win.onCloseRequested(async (event) => {
        const projectId = get(activeProjectId);
        if (projectId) saveProjectState(projectId);

        if (get(closeBehavior) === 'minimize') {
          event.preventDefault();
          await win.minimize();
        }
      }).then((u) => { unlistenClose = u; });
    }

    // Lock window scrolling to prevent viewport shifting when dragging elements/selection
    const handleScroll = () => {
      if (window.scrollX !== 0 || window.scrollY !== 0) {
        window.scrollTo(0, 0);
      }
    };
    window.addEventListener('scroll', handleScroll, { passive: true });

    // Apply persistent zoom level via container transform
    const unsubscribeZoom = uiZoom.subscribe((zoom) => {
      if (typeof document !== 'undefined') {
        document.documentElement.style.setProperty('--ui-zoom-percent', `${zoom}`);
      }
    });

    let activeShortcuts: KeyboardShortcut[] = [];
    const unsubscribeShortcuts = userShortcuts.subscribe((val) => {
      activeShortcuts = val || [];
    });

    // Intercept zoom keyboard shortcuts
    const handleKeyDown = (e: KeyboardEvent) => {
      const zoomInShortcut = activeShortcuts.find(s => s && s.id === 'zoomIn');
      const zoomOutShortcut = activeShortcuts.find(s => s && s.id === 'zoomOut');
      const resetZoomShortcut = activeShortcuts.find(s => s && s.id === 'resetZoom');

      if (zoomInShortcut && matchShortcut(e, zoomInShortcut.keys)) {
        e.preventDefault();
        zoomIn();
      } else if (zoomOutShortcut && matchShortcut(e, zoomOutShortcut.keys)) {
        e.preventDefault();
        zoomOut();
      } else if (resetZoomShortcut && matchShortcut(e, resetZoomShortcut.keys)) {
        e.preventDefault();
        uiZoom.set(100);
      }
    };
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      window.removeEventListener('keydown', handleKeyDown);
      unsubscribeZoom();
      unlistenClose?.();
      unsubscribeShortcuts();
      unsubDailyNote();
      unsubFrost();
      unsubBgEnabled();
      unsubBgOpacity();
      unsubBgBlur();
    };
  });
</script>

<BackgroundMedia />
<AppShell />

<CommandPalette />
<Toasts />

{#if $settingsOpen}
  <SettingsModal onclose={closeSettings} />
{/if}

{#if $quickCaptureOpen}
  <QuickCaptureModal onclose={closeQuickCapture} />
{/if}

{#if $envManagerOpen}
  <EnvManager />
{/if}

{#if $newWorkspacePromptOpen}
  <WorkspaceNameModal />
{/if}

{#if !$onboardingCompleted}
  <OnboardingWalkthrough />
{/if}

{#if $pendingPermissionRequest}
  <MicrophonePermissionDialog />
{/if}
