// src/lib/components/layout/StatusBar.tsx
import type { CSSProperties } from 'react';
import { useWorkspaceStore } from '$lib/stores/zustand/workspace';
import { useEditorStore } from '$lib/stores/zustand/editor';
import { useLayoutStore } from '$lib/stores/zustand/layout';
import { setSidebarTab, setActiveView } from '$lib/stores/layout';
import { branchInfo } from '$lib/stores/gitBranch';
import { devpet } from '$lib/stores/devpet';
import { useSettingsStore } from '$lib/stores/zustand/settings';
import PetAvatar from '$lib/components/pet/PetAvatar.tsx';
import { useStore } from '$lib/react/useStore';
import './StatusBar.css';

const viewColors: Record<string, string> = {
  editor: 'var(--accent)',
  terminal: 'var(--success)',
  preview: 'var(--accent)',
  settings: 'var(--accent)',
};

export default function StatusBar() {
  const project = useWorkspaceStore((s) => (s.activeProjectId ? s.projects.get(s.activeProjectId) ?? null : null));
  const file = useEditorStore((s) => s.activeFile);
  const cache = useEditorStore((s) => s.fileCache);
  const line = useEditorStore((s) => s.activeLine);
  const column = useEditorStore((s) => s.activeColumn);
  const layoutState = useLayoutStore();
  const zoom = useSettingsStore((s) => s.uiZoom);
  const branch = useStore(branchInfo);
  const pet = useStore(devpet);

  const activeFileInfo = file ? cache.get(file) : null;
  const languageLabel = activeFileInfo
    ? activeFileInfo.language.charAt(0).toUpperCase() + activeFileInfo.language.slice(1)
    : '';
  const activeFileIsText = activeFileInfo?.kind === 'text';

  return (
    <footer className="statusbar">
      <div className="sb-left">
        <span
          className="sb-view-badge"
          style={{ '--vc': viewColors[layoutState.activeView] ?? '#06b6d4' } as CSSProperties}
        >
          {layoutState.activeView}
        </span>

        {project && (
          <>
            <span className="sb-sep">.</span>
            <span className="sb-item">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z" />
              </svg>
              {project.name}
            </span>
          </>
        )}
        {branch?.current && (
          <>
            <span className="sb-sep">.</span>
            <span className="sb-item sb-branch" onClick={() => setSidebarTab('git')} title="Switch branch">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="6" y1="3" x2="6" y2="15" />
                <circle cx="18" cy="6" r="3" />
                <circle cx="6" cy="18" r="3" />
                <path d="M18 9a9 9 0 01-9 9" />
              </svg>
              {branch.current}
            </span>
          </>
        )}
      </div>

      <div className="sb-right">
        <button
          type="button"
          className="sb-item sb-pet"
          onClick={() => setActiveView('pet')}
          title={`${pet.name} (Lvl ${pet.level}) | Status: ${pet.status} | WPM: ${pet.wpm}. Click to open playground.`}
          aria-label="Open DevPet playground"
        >
          <div className="sb-pet-avatar">
            <PetAvatar type={pet.type} status={pet.status} skin={pet.skin} />
          </div>
          <span className="sb-pet-text">{pet.name}</span>
        </button>
        <span className="sb-sep">.</span>

        {activeFileInfo && (
          <>
            {activeFileIsText && (
              <>
                <span className="sb-item">
                  Ln {line}, Col {column}
                </span>
                <span className="sb-sep">.</span>
              </>
            )}
            <span className="sb-item">{languageLabel}</span>
            <span className="sb-sep">.</span>
          </>
        )}
        {(!activeFileInfo || activeFileIsText) && (
          <>
            <span className="sb-item">UTF-8</span>
            <span className="sb-sep">.</span>
            <span className="sb-item">LF</span>
            <span className="sb-sep">.</span>
          </>
        )}
        <span className="sb-item zoom-indicator">{zoom}%</span>
      </div>
    </footer>
  );
}

// src/lib/components/layout/StatusBar.svelte
<script lang="ts">
  import { activeProject } from '$lib/stores/workspace';
  import { activeFile, fileCache, activeLine, activeColumn } from '$lib/stores/editor';
  import { layout, setSidebarTab, setActiveView } from '$lib/stores/layout';
  import { uiZoom } from '$lib/stores/settings';
  import { branchInfo } from '$lib/stores/gitBranch';
  import { devpet } from '$lib/stores/devpet';
  import PetAvatar from '$lib/components/pet/PetAvatar.svelte';

  $: activeFileInfo = $activeFile ? $fileCache.get($activeFile) : null;
  $: languageLabel = activeFileInfo
    ? activeFileInfo.language.charAt(0).toUpperCase() + activeFileInfo.language.slice(1)
    : '';
  $: activeFileIsText = activeFileInfo?.kind === 'text';

  const viewColors: Record<string, string> = {
    editor: 'var(--accent)',
    terminal: 'var(--success)',
    preview: 'var(--accent)',
    settings: 'var(--accent)',
  };
</script>

<footer class="statusbar">
  <div class="sb-left">
    <span
      class="sb-view-badge"
      style="--vc: {viewColors[$layout.activeView] ?? '#06b6d4'}"
    >
      {$layout.activeView}
    </span>

    {#if $activeProject}
      <span class="sb-sep">.</span>
      <span class="sb-item">
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/>
        </svg>
        {$activeProject.name}
      </span>
    {/if}
    {#if $branchInfo?.current}
      <span class="sb-sep">.</span>
      <!-- svelte-ignore a11y_click_events_have_key_events -->
      <!-- svelte-ignore a11y_no_static_element_interactions -->
      <span class="sb-item sb-branch" onclick={() => setSidebarTab('git')} title="Switch branch">
        <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="6" y1="3" x2="6" y2="15"/><circle cx="18" cy="6" r="3"/><circle cx="6" cy="18" r="3"/>
          <path d="M18 9a9 9 0 01-9 9"/>
        </svg>
        {$branchInfo.current}
      </span>
    {/if}
  </div>

  <div class="sb-right">
    <button
      type="button"
      class="sb-item sb-pet"
      onclick={() => setActiveView('pet')}
      title="{$devpet.name} (Lvl {$devpet.level}) | Status: {$devpet.status} | WPM: {$devpet.wpm}. Click to open playground."
      aria-label="Open DevPet playground"
    >
      <div class="sb-pet-avatar">
        <PetAvatar type={$devpet.type} status={$devpet.status} skin={$devpet.skin} />
      </div>
      <span class="sb-pet-text">{$devpet.name}</span>
    </button>
    <span class="sb-sep">.</span>

    {#if activeFileInfo}
      {#if activeFileIsText}
        <span class="sb-item">Ln {$activeLine}, Col {$activeColumn}</span>
        <span class="sb-sep">.</span>
      {/if}
      <span class="sb-item">{languageLabel}</span>
      <span class="sb-sep">.</span>
    {/if}
    {#if !activeFileInfo || activeFileIsText}
      <span class="sb-item">UTF-8</span>
      <span class="sb-sep">.</span>
      <span class="sb-item">LF</span>
      <span class="sb-sep">.</span>
    {/if}
    <span class="sb-item zoom-indicator">{$uiZoom}%</span>
  </div>
</footer>

<style>
  .statusbar {
    height: 26px;
    background: transparent;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 14px;
    font-size: 11.5px;
    color: var(--text-secondary);
    flex-shrink: 0;
    letter-spacing: 0.2px;
  }

  .sb-left, .sb-right {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .sb-view-badge {
    font-size: 10px;
    font-weight: 600;
    text-transform: capitalize;
    color: var(--vc);
    letter-spacing: 0.5px;
    padding: 1px 6px;
    border-radius: 9999px;
    background: color-mix(in srgb, var(--vc) 12%, transparent);
    border: 1px solid color-mix(in srgb, var(--vc) 18%, transparent);
  }

  .sb-sep {
    opacity: 0.4;
    font-size: 11px;
    color: var(--text-muted);
  }

  .sb-item {
    display: flex;
    align-items: center;
    gap: 4px;
    color: var(--text-secondary);
    transition: color 0.15s ease;
  }

  .sb-item:hover {
    color: var(--text-primary);
  }

  .sb-item svg {
    width: 13px;
    height: 13px;
  }

  .zoom-indicator {
    min-width: 36px;
    text-align: center;
    font-variant-numeric: tabular-nums;
  }

  .sb-branch { cursor: pointer; }
  .sb-branch:hover { color: var(--accent); }

  /* DevPet status bar styling */
  .sb-pet {
    cursor: pointer;
    gap: 6px;
    height: 100%;
    display: flex;
    align-items: center;
    padding: 0 4px;
    border: 0;
    border-radius: 4px;
    background: transparent;
    font: inherit;
    transition: background 0.15s ease, color 0.15s ease;
  }

  .sb-pet:hover {
    background: var(--bg-hover);
    color: var(--accent);
  }

  .sb-pet-avatar {
    width: 16px;
    height: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
  }
  
  .sb-pet-avatar :global(.pet-svg) {
    max-width: 16px !important;
    max-height: 16px !important;
  }
  
  .sb-pet-text {
    font-size: 11px;
    font-weight: 500;
  }
</style>
