// src/lib/components/toolbox/ToolboxPanelLazy.tsx
import { lazy, Suspense } from 'react';

// Lazy boundary for ToolboxPanel — the React lazy boundary for
// dynamic import. Loaded on demand; renders nothing until ready
// (matching the original `{#if Panel}` gate) so call sites stay unchanged.
const ToolboxPanel = lazy(() => import('./ToolboxPanel.tsx'));

export default function ToolboxPanelLazy() {
  return (
    <Suspense fallback={null}>
      <ToolboxPanel />
    </Suspense>
  );
}

// src/lib/components/toolbox/ToolboxPanelLazy.svelte
<!--
  Lazy boundary for ToolboxPanel — see EditorPanelLazy for the rationale. Loaded
  on demand; rendered in place of ToolboxPanel so call sites stay unchanged.
-->
<script lang="ts">
  import type { Component } from 'svelte';
  import { onMount } from 'svelte';

  let Panel = $state<Component | null>(null);
  onMount(async () => {
    Panel = (await import('./ToolboxPanel.svelte')).default as unknown as Component;
  });
</script>

{#if Panel}
  <Panel />
{/if}
